pihole:
    image: pihole/pihole
    container_name: pihole
    env_file:
       - .env
    volumes:
      - /home/vannak/docker/pihole/config:/etc/pihole
      - /home/vannak/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped
