version: '3.8'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=America/Bogota
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - /home/vannak/docker/crafty/data:/crafty/data
        - /home/vannak/docker/crafty/logs:/crafty/logs
        - /home/vannak/docker/crafty/servers:/crafty/servers
        - /home/vannak/docker/crafty/config:/crafty/app/config
        - /home/vannak/docker/crafty/import:/crafty/import