version: '3.8'

services:
  uptime-kuma:
      restart: always
      ports:
          - 3001:3001
      volumes:
          - /home/vannak/docker/uptime-kuma/data:/app/data
      container_name: uptime-kuma
      image: louislam/uptime-kuma:1
