version: '3.8'

services:
  psql:
    image: postgres:latest
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: