version: '3.8'

services:
  psql:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - /home/vannak/docker/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
